### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by sqlshep** [ghandic/nbconvert#4]
I am sure this is painfully obviuos, but where does this happen?  "You do this by adding the uri into the git plugin installer (ghandic/nbconvert)"  Not seeing in in wordpress after uploading the WP Pusher plugin, and don't see it on github, and dont see it as an option for add plugin either. 

**Update**:  As usual after asking i figured it out, however, i have a wrap issue with results.  Check out.  I will look at my css, but may need some help. 

**Resolved:**  For what its worth, i modified the .dataframe css to the following to prevent data bleed into the margins.  Probably more than needed, but once i got it working i stopped touching it. 

div.notebook div.nbconvert div .dataframe {
border:0px dashed;
display: block;
overflow-x: auto;
height: 500px;
overflow-y: auto;
white-space: nowrap;
}

https://sqlshep.com/?p=1174

Shep

**Comment by ghandic** [comment]
Thanks for updating Shep! I'll close the issue but keep it here for others.
